spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gameservice?characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    

  devtools:
    restart:
      exclude:  static/**,public/**
      enabled:  true