server:
  port: 88
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: embedded
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
    url: jdbc:mysql://localhost:3306/gameservice?characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    platform: mysql
    
  devtools:
    restart:
      exclude:  static/**,public/**,img/**
      enabled:  true
      
  redis:
    client-name: redis0
    database: 0
    timeout: 3000
    sentinel:
      master: mymaster
      nodes:
      - 192.168.2.121:26381
      - 192.168.2.121:26382
    lettuce:
      pool:
        max-active: 8

  redis2:
    client-name: redis2
    database: 0
    timeout: 3000
    sentinel:
      master: mymaster
      nodes: 192.168.2.121:26381
#      - 192.168.2.121:26382
    lettuce:
      pool:
        max-active: 8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      
# Logger Config
#logging:
#  level:
#    com.baomidou.mybatisplus.samples.quickstart: debug
    