spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gameservice?characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    
    initialization-mode: always
    schema:
    - classpath:sql/schema.sql
    data:
    - classpath:sql/data.sql

  devtools:
    restart:
      exclude:  static/**,public/**
      enabled:  true